### ISSUE TITLE
Make routes clickable

### ISSUE THREAD

**Issue by dittaeva** [waymarkedtrails/waymarked-trails-site#29]
At least on the desktop version it would be useful to either be able to click on any part of the route, or on the label, to show the info-box about that route.

On the mobile version I'm not sure, could be problematic because of panning, etc.

**Comment by jschleic** [comment]
Really cool idea. I'm working on this.

As a first step it can be tested while the route browser is open: [branch clickable-routes](/jschleic/waymarked-trails-site/tree/feature-clickable-routes).

Open Questions:
* What should happen, when several routes are above each other? Is a random selection feasible? How can the "best" route be detected?
* How can we keep the data size down? For the route browser, there are just top 20 routes displayed, should the same routes be clickable (then also loaded when the route browser is closed)?
* Should the local (higher zoom) data without label be excluded? Or are they clickable, too?

**Comment by lonvia** [comment]
I was planning on switching to vector tiles at some point and have actually started a few tests just last week.  I've uploaded the current state to [the vector-tiles branch](https://github.com/lonvia/waymarked-trails-site/tree/vector-tiles). This would be my preferred route also for clickable routes as it maximizes cache use in the browser.

Maybe we could join forces on this? We'd need to define a vector tile content that is useful for both, clicking and rendering. The actual rendering is probably going to take a bit longer to implement (the shield placement is rather tricky) but it would be perfectly fine to already introduce the vector tiles for the clicking feature and then switch to vector rendering when it is ready.

Some thoughts to the questions you raised: My plan was to have a single vector tile set at zoom 12. That is the first level where all routes are visible (so nicely works around the problem of routes invisible on the map). Below that, it would remain a static map. Levels above simply reuse the level 12 tiles. You can see that implemented in the branch above. 

As long as there are bitmap tiles used, you can only detect clicks on lines. I'd really just present the usual route list with all choices if routes overlap and the route details directly if there is only a single route. I was thinking that the shields should be clickable to avoid having to make a choice between overlapping routes but that is only possible once we have vector rendering and place the shields in the browser.

**Comment by jschleic** [comment]
Yes, that sounds as the way to go.

I'm happy with the data structure of the json tiles (relations as property of each segment):
[branch vector-tiles](/jschleic/waymarked-trails-site/tree/vector-tiles).

So, for the beginning the vectorTiles layer would have style:null and just be used for click-detection?

Would it be feasible, to use the same data for "hovering" as well, so that the "segments" vector layer can be replaced by the new vectorTiles layer?

**Comment by lonvia** [comment]
> I'm happy with the data structure of the json tiles (relations as property of each segment):
branch vector-tiles.

Ok. At some point I'll probably have to add more than just the id for the relations, so it would be a good idea to have a function get_relation_list() that wraps the extraction of the relation ids.

> So, for the beginning the vectorTiles layer would have style:null and just be used for click-detection?

You probably want your own layer. At the moment it looks like the rendering will need multiple layers that just share the same tile source because otherwise there are strange rendering artifacts where the segments end.

> Would it be feasible, to use the same data for "hovering" as well, so that the "segments" vector layer can be replaced by the new vectorTiles layer?

Good point. We cannot completely get rid of the 'segments' API call because the hovering should also work for zoom levels 0 - 11. But for level 12+ the layer should definitely be using the vector tiles as a data source. Would it make sense to hook the clickable callback directly into the 'segments' layer?

**Comment by Hufkratzer** [comment]
Some strange clicking results near junctions:

* open http://riding.waymarkedtrails.org/#?map=18!51.7095!14.8555
* click on the right corner of the plack route (near A) -> a route list with just that one black route opens. Does that make sense? Shouldn't the detail view appear?
![ab](https://cloud.githubusercontent.com/assets/5958184/20012295/f2f6c0da-a2ae-11e6-8e90-0487236b45e4.jpg)

* click at the green dot (near B) -> a route list with the 2 routes opens. Shouldn't the detail view for the green one appear?

*  open http://riding.waymarkedtrails.org/#?map=18!51.3647!15.3107 -> you should see just one route (with symbol orange dot):
* click on the route somewhere in the middle of the screen -> a route list appears that lists this route but also a blue one that is not visible on the screen (at least not on my screen):
![c](https://cloud.githubusercontent.com/assets/5958184/20012405/562ad8a8-a2af-11e6-915d-8a74dfdc854c.jpg)

**Comment by jschleic** [comment]
For the second and third issue (B) and the yellow dot see #258.

The first one could be fixed in Javascript as well (not adding duplicate ids), but I first want to check that the vroute layer source is fine.

**Comment by Hufkratzer** [comment]
I just found [this](https://mapa-turystyczna.pl) map where the form of the cursor indicates if it is positioned on something clickable or not. Perhaps you want to adopt this? :bulb:

**Comment by jschleic** [comment]
Thanks @Hufkratzer for the hint. As discussed in #256 the cursor change is only possible, once the routes are rendered in the browser. For the moment the visible "lines" and shields still are static png graphics.
