### ISSUE TITLE
HTTP errors for many tiles

### ISSUE THREAD

**Issue by don-vip** [waymarkedtrails/waymarked-trails-site#319]
Tiles are unstable:
https://josm.openstreetmap.de/jenkins/job/JOSM-Imagery-Integration/410/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.imagery/ImageryPreferenceTestIT/testImageryEntryValidity_Waymarked_Trails_Cycling_/history/

![image](https://user-images.githubusercontent.com/596867/62741272-a0ca6900-ba3a-11e9-873c-bab4a00e05b3.png)

We get errors for many tiles, for example:
https://tile.waymarkedtrails.org/cycling/12/2047/1362.png

**Comment by don-vip** [comment]
Sometimes the error concerns other pages:

https://hiking.waymarkedtrails.org/en/help/legal -> HTTP 503
https://cycling.waymarkedtrails.org/en/help/legal -> HTTP 503

These are random issues.

**Comment by lonvia** [comment]
I'm aware that there are stability issues on the server. Not entirely sure about the causes yet. Apache is not exactly helpful when it comes to 503s.

I've blocked requests without referrer and a simple Mozilla user agent yesterday, to get rid of a couple of scrapers . That's why you can't directly look at the tiles. Doesn't seem to have helped though, so I've removed it again.

**Comment by lonvia** [comment]
I believe this fixed itself. Still not entirely sure what the issue is as Apache doesn't log anything at all about these 503s, not even in the access logs.
