### ISSUE TITLE
Render cyclenode-Neworks in a separtly colour

### ISSUE THREAD

**Issue by streckenkundler** [waymarkedtrails/waymarked-trails-site#322]
Hi.
I think it is now necessary that bicycle-node networks must be presented separately in the cycle path map. In my opinion, these networks are a completely separate category, regardless of rcn or lcn or so. These bike networks are being set up more and more frequently, but in my opinion they collide with real thematic cycle routes.
These are usually always recognizable with node rcn_ref=* and relation type=route + cycle_network=*
We can also exchange information in german by e-mail if necessary. 

Greetings from the Spreewald

streckenkundler

**Comment by lonvia** [comment]
This has been discussed briefly in #201 already. I need something that identifies that the _relations_ are part of a node network. The presence of `rcn_ref` nodes is not sufficient. The `cycle_network` tag description in the wiki indicates that this is not a tag for node networks either.

Node networks are used in many countries. The Netherlands community is currently discussing tagging as well. Please start a discussion on an international mailing list to reach an agreement on a common tagging schema. 

CC @pelderson who has been filing tickets for the Netherlands. You really want to talk to the German community as well.

**Comment by streckenkundler** [comment]
A contribution tree in the German Forum is here: [https://forum.openstreetmap.org/viewtopic.php?id=31239](url) In my observation, network=rcn should be replaced here with something else like network=cnn. I fear, however, that it will be difficult to reach a consensus.
At the moment I can reasonably easily determine nodes and/or relationships with the query [http://overpass-turbo.eu/s/LOO](url) For Brandenburg, only these networks are determined.

**Comment by lonvia** [comment]
`network=cnn` sounds like a good start. Create a wiki page with a proposal and put it up for discussion. Then we'll see what the different opinions are.

**Comment by pelderson** [comment]
@streckenkundler The Dutch forum has this under consideration too. Would you like me to report current state to the German forum? Maybe we could present @lonvia with a common proposal.

**Comment by pelderson** [comment]
The Dutch have discussed this at length. Bottom line we propose simply to
add a tag network_type=node_network to the route relations of the node
networks.
Nodes do not need this tag, the fact that they have the xxn_ref tag says it
all.

This allows node networks to be defined for all modes of transportation and
all geographical scopes. The setup can handle other network_types should
they arise; other modes of transportation; and other geographical scopes if
necessary (so intercontinental drone hub_networks, no problem!)

Node netwok checking-site knooppuntnet.be/knooppuntnet.nl (the site
formerly known as vmarc.be, i.e. user vmarc) has indicated it is an
easy-to-implement  solution.
*We think waymarkedtrails can work with this too; if not we like to hear
why.*
We think maybe the network relation with all the routes and nodes in it is
no longer necessary. That is in the current system the main
pain-in-the-butt for node network maintenance, and nobody really used it.

Existing base does not need retagging, just add the extra tag to the node
network relations. In Nederland this can be done quick and easy because we
have no regional linear routes defined: all rwn routes are node_network
routes. In Germany I think there is a mix of linear and node rwn routes, so
it's a project but I think not a large or difficult one.
Adding the extra tag changes nothing for the current rendering, so existing
data users can keep their system in place while developing handling of the
new system, then changeover at their own time.

Fr gr Peter Elderson


Op ma 26 aug. 2019 om 09:28 schreef Sarah Hoffmann <notifications@github.com

**Comment by pelderson** [comment]
Hi
We have dicussed this further on the tagging mailing list, the German OSM forum, and the Dutch OSM forum. The Belgium OSM forum has not responded, but vmarc has responded on the Dutch OSM forum. This is the result: 
The Dutch mappers will add the tag network:type=node_network to all junction nodes and node2node route relations belonging to a node network, and also to the node network relation. 

This applies to all recreational routes. (Horseriding, canoe, mtb, inline_skating node networks are emerging.)

That's it! We will document this on the relevant wiki-pages. 

NB. In principle, node networks can now be made on the for geographical scopes: local, regional, national and international. In the Netherlands, cycling node networks are national, but walking node networks are present at local, regional and national levels. In Germany, some local cyclingh node networks are present. Regional linear routes are already present in Germany, and can now appear in Netherlands as well. Some international walking routes are developing as node networks, with wellknown cities or places functioning as nodes.

So if special rendering is implemented for node networks, all 4 regional scopes will need to be considered, I think.

**Comment by streckenkundler** [comment]
Thank you for your contribution. I too think that the solution presented is the best. I really like her. It does not change the existing tagging, but extends it to include the junction networks. I will quote your lines in the German forum and write a positive vote.  Finally, the wiki has to be adjusted accordingly.

**Comment by pelderson** [comment]
One additional comment. We found series of nodes tagged with XXn_ref =* which are not part of a node network. E.g. lpn_ref nodes representing numbered poles to be passed in sequence for canoe routes. Like numbered waymarks. For rendering, we would still want those to appear on the map! So we think for rendering, the network:type=node_network tag should only be considered for the node2node routes, not for the nodes.

**Comment by streckenkundler** [comment]
I think if the node can be clearly indentified as part of a node network, then it can also get network:type=node_network. Often these are part of a node2node route and/or part of a network relation. This can then be separated from other XXn_ref* uses.

**Comment by pelderson** [comment]
**Status report**
All elements of all recreational node networks in the Netherlands now have the tag network:type=node_network. The maintenance site https://www.knooppuntnet.nl is being modified to check for the tag. 
I think it is up to the German and Belgian communities to add the tag to ‘their’ node networks. Of course, we would be glad to help out, when asked.

**Comment by streckenkundler** [comment]
For your information:
all cycle-node-networks in Brandenburg are supplemented with network:type=node_network. I also looked at the relations with the maintenance site https://www.knooppuntnet.nl and found some other errors in some relations. However, I have the impression that the networks are not yet fully covered. In South Brandenburg, the nets are only partially recorded, as they are only just emerging.
Other networks in Germany have also been added in the meantime.

Now all that is missing is a corresponding rendering.

**Comment by pelderson** [comment]
As of now, all nodes, routes and network relations of registered node networks (cycling, walking, horse, canoe, motorboat, inlineskating) in Germany, Belgium and Nederland have the tag network:type=node_network. Documented here: https://wiki.openstreetmap.org/wiki/Key:network:type 
Taginfo: https://taginfo.openstreetmap.org/search?q=network%3Atype
Many Wiki pages about tagging recreational routes have already been updated, this process is still going on.

**Comment by lonvia** [comment]
I have just read the discussion on the tagging list and I don't see a single voice agreeing with your proposal. There were a lot of good arguments that would have been worth considering. I do have an implementation for a new rendering but I am really hesitant to put it into production given the state of affairs. We already have a `network` tag that was not thought out very well. It really would have been worth to not repeat the mistake.

**Comment by streckenkundler** [comment]
I just flew over the disscussion. I miss the realisation that all cycle nodes networks are simply a completely separate category, which complement conventional thematic bike routes and both overlap. But this may also be due to the fact that node networks are a special thing in D, NL, B and F. Therefore, on tagging, don't read a real alternative how such node networks and their routes can be separated from thematic bike routes and evaluated separately.

As far as I can see, all captured node networks have received the network:type=node_network. In the case of further registrations here in South Brandenburg, it will continue to be actively used.
The nice thing is that our Dutch friends have an excellent evaluation tool for error testing:
https://www.knooppuntnet.nl/en/

By the way, the leisure map plans to show nodes in the near future... See: https://forum.openstreetmap.org/viewtopic.php?pid=762937#p762937

Greetings, Sven

**Comment by pelderson** [comment]
We have considered and answered all arguments. In particular, the
suggestion to use a new network=* value for each mode of transport was
answered: that would in fact further burden the network tag with yet
another aspect, and lose the geographic extent information. Why do you fear
this is a mistake? What is wrong with the network tag for recreational
routes?
The additional tag completely separates regular routes from node networks,
for all geographical ranges and all modes of transport.
In the meantime, almost all node networks have been additionally tagged
with the network:type=node_network tag, the tag has been documented, and
the checking sites knooppuntnet.be and knooppuntnet.nl now use the tag and
check for it.

Can I see the rendering you have created somewhere?

Thanks.

Fr gr  Peter Elderson


Op do 10 okt. 2019 om 22:48 schreef Sarah Hoffmann <notifications@github.com

**Comment by streckenkundler** [comment]
I fully agree with Peter. I see no other solution either. Comparing some statements on the tagging maling list, I think the use of network for cycle node networks in parts (or complete?) would lead to a redefinition of network. 
That would be the worst of all possible alternatives.
The tagging, the display and also the error check work very well. With knooppuntnet.nl, it is also possible to align the recorded networks in tagging.

Sven

**Comment by lonvia** [comment]
On a procedural level, there was barely two weeks between your first message on tagging@ and the mass edit that introduced the new tag. Why the hurry? I happened to have been in vacation at the time, so was basically confronted with a done deal after coming back. I know that others felt the same. I was approached by a mapper just this weekend who had done the initial mapping of one of the networks in Brandenburg and who was just as surprised (in the negative sense of the word) about the mass edit. 

On a technical level, there are a couple of points. First, I don't buy the argument of geographical scope. The 'network' tag describes the geographic importance of a single route, not on which scale the operator works. The route between two nodes is always very local in the node networks we have so far and I have no idea of which "international walking routes" you speak.

You also say that the walking node network in the Netherlands is managed locally. Does that mean that every county/town comes up with their own network and networks of neighbouring counties may be overlapping? Then this wouldn't be covered at all by the new tagging scheme because then we need a way to identify different networks (on the same "global scope", so the network tag is no help here).

Personally, I'd say that when you consider that the `network` tag expresses the geographic scope of the route relation, then a relation in a node network fits very well below the local scope. It is exactly that, a route even smaller than a local cycling route because it makes up only a part of it. If you don't like the mode of transport encoded in the `network` tag (and I wholeheartedly agree with that), then there was no need to repeat the mistake and simply define `network=node`.

I also see a problem with the key name `network:type`. It is rather vague on what it actually should contain. This kind of tags have a high chance of being misused. So it would have been worth to stop and think what a network type actually can be. You mentioned color-coded routes but these are actually already covered with the current tagging schema.

All that said, the new tag is not the end of the world. It is fairly easy to use and clear to apply. I'm just thinking that we might have come up with something better. There is a reason that we have established procedures that involve writing a proposal, discussing and voting on it. It gives people time to think about the options, find out about similar (or opposing) uses in the rest of the world and hopefully come up with something sustainable.

**Comment by pelderson** [comment]
The network=XXn tag contains mode of transport and geographical scope. No
change there, all the information is preserved. We did not want to put the
network system (organisation/configuration/usage rules) in there as well,
because then you would have three aspects in one tag (multiplying tthe
possible combnations and values needed), and you would have to  implement
alternatives for all the existing information. This to correct an exception
that only existed in Belgium, Germany and the Netherlands. This is
overkill, it  would make the network=* tag worse instead of better, and it
would force changes to routes worldwide. A no-go, I think. If someone wants
to propose a complete system change, our addition does not stand in the way
and could even help.

Node networks can be on different scales, they can overlap or connect, and
change all the time. On the road in Belgium and Netherlands eventually one
national node network system per mode of transport will be present on the
road. This is happening now and it's moving fast. In the end the network
relation for these will be national, some will remain regional, but the
node2node relations are mostly local. Node networks for transport modes
other than foot and bicycle are different, this is still in development,
but now we have lifted the network-system out of the network=* tag, we can
handle tagging of all variants for all 4 geographical ranges and all
defined transport modes.

Other types of network different from node_networks are present and
developing on the road, for different modes of transport, in some regions
of the Netherlands. Aso in Germany in particular for cycling networks in
and around big cities. The network:type=* tag was an existing tag in the
database, and it allows different types to emerge and be handled when
needed. The existing usage did not conflict with our use.

The additional tagging is now documented for all transport modes and in
multiple languages. The tagging has been done. I myself was surprised and
not happy because some impatient taggers had already gone ahead even before
I finished the discussions. But so be it. Maybe the tag name could have
been better (I think it could be more specific about what is meant by
type). Tagging the network relation AND all the nodes AND all the node2node
relations seems unnecessary to me, but it's not a big issue. I think the
network relation can be eliminated: it just causes a lot of tagging work
and nobody uses it for rendering or routing, but they are already there so
that's for another time. This solution does not get in the way of such
future changes.

Since the problem was only in the three countries which caused the problem
themselves, voting was not really an option for most taggers involved. Some
were against even mentioning it on the tagging list, but I found that I had
do at least that. So I did.

If you see actual problems with the node_network tagging now in effect,  I
would like to know what problems.

Thanks for your help and feedback! And I still would like to see the
intended rendering you have created!

Fr gr Peter Elderson

PS

Op ma 14 okt. 2019 om 10:12 schreef Sarah Hoffmann <notifications@github.com

**Comment by lonvia** [comment]
Could you please elaborate on

> Node networks can be on different scales, they can overlap or connect, and change all the time.

Do you have an existing example of an area where there are networks of different scales _in the same area_? How does that look like with the waymarking? How are overlapping node networks marked in the nature? How does it look like when they overlap? How do I know what network a node belongs to when it is in an area where such an overlap exists? How do connections between different node networks work? Do they have any special tagging for those?

**Comment by pelderson** [comment]
Sarah Hoffmann:

> Could you please elaborate on
>
> Node networks can be on different scales, they can overlap or connect, and
> change all the time.
>
> Do you have an existing example of an area where there are networks of
> different scales *in the same area*? How does that look like with the
> waymarking? How are overlapping node networks marked in the nature? How
> does it look like when they overlap? How do I know what network a node
> belongs to when it is in an area where such an overlap exists? How do
> connections between different node networks work? Do they have any special
> tagging for those?
>
> All hiking and cycling node networks in the Netherlands still are
network=rwn and network=rcn. A typical area for the walking node networks
development is Noord-Brabant.
https://hiking.waymarkedtrails.org/#search?query=veghel&map=9!51.5717!6.024

First, some cities started separate node networks. Then some of them
interconnected. Later, the province took control, intending to cover the
whole province with interconnected local node networks. Then some regions
within the province were defined to replace the interconnected networks
with regional ones. Now the whole province is covered with one big walking
node network, operated and maintained by one provincial office dedicate to
all types of recreational routes and networks. For internal administration
they still use regions and city names, but that is no longer applied to the
signposts and waymarks.
OSM has tried to keep up with al the developments, still does, but all the
development stages are still present in OSM. The regional node network
West-Noordbrabant still exists, it has the same nodes and routes also
contained in a number of local node networks. The new situation (one big
node network) has not been implemented in OSM, mainly because such large
network relations are very hard to maintain.

How it looks? On the ground you just have numbered node signposts. Routes
in between are waymarked with stickers and signposts with arrows, without
numbers. On waymarkedtrails you render the numbered nodes, and the
node2node routes are rendered according to the network tag, so all orange.
I think there are dupicate node2node routes, but you can't see that of
course. On the ground you don't see anything of the old/new administrative
networks. Information panels of local collections have been replaced with
new panels; the local networks have been reused.

The node in OSM is not tagged with network information. A node tagged with
rwn_ref=* can belong to several walking node network relations.

Connecting routes between different node networks are now entered in both
node network relations with the role connection. This is just for OSM
maintenance. On the ground you see nothing different, except maybe the
waymark style may change.

**Comment by streckenkundler** [comment]
Hi, here is a typical example from my Spreewald: cycle node number 77 with reference to three more nodes (49, 78, 79):
https://www.die-spreewaldbahn.de/spezial/OSM_Err/Nr77_3.jpg
https://www.openstreetmap.org/node/32895169
You will see a lot of more information on a signpost:
a NordicWalking route (black route)
two local hiking routes (yellow dot and green bar)
one local hiking route (red bar)
four regional cycle routes (Spreeradweg, Gurkenradweg, Sorbische Impressionen, Fürst Pückler-Radweg)
the three cycle nodes

All this on a signpost with the number 189. In other counties, a second number and/or an emergency rescue point may be added.

I see cycle node networks as a signposted and referenced base network, which represents a completely separate class in rendering as well as in evaluation. Theme bike routes usually use parts of this network, but are something of their own.

What alternative would there be to capture such node networks as a network without conflicting with such theme cycle routes, in the presentation, in the separate evaluation and error checking? I can't think of an alternative without redefining the entire tagging scheme... The elegant thing is that node networks are now defined separately, without which the previous tagging has been changed. It has only been extended. All existing other routes have not been changed.

Because of the suboptimal definition of the network tag, such node networks without their own definition can hardly be evaluated separately at the moment. A redefinition of the network tag would be the worst case, even an extension...

The general problem is already apparent in the rendering: network=rcn on the routes currently ensures an over-representation of this rendering class. If you use network=lcn alternately, the problem shifts without it being resolved.

Sven

PS: alternatively I would explain this more precisely by PN in German (that would suit me with my bad English)

**Comment by lonvia** [comment]
I'm afraid we are really misunderstanding each other here. I did not ask how node networks work in general. I do know them, I've cycled along the node network in the Netherlands.

What I have been trying to find out is if two node networks with different signage may overlap each other. The signage is the key here: are these two node networks recognisable as being different for the user of the network and is it important for routing oneself along the network? Because then the map might not only need to show that there is a node network but also what signage it carries. The current proposal doesn't consider that. (That operatorship has changed in the Netherlands from local to provincal authorities is interesting but largely irrelevant for the map display.) 

The other question I asked was: are there relations with  `network:type=node`+`network=lwn` and  relations with  `network:type=node`+`network=rwn` in the same area at the same time. Again, this has nothing to do with the operator. It's basically the same issue as with overlapping above. The reason I ask separately is because @pelderson insists that `network:type` and `network` are different dimensions of a route relation. And I wanted to understand what this means. 

Anyway, the more I think about it, the more I'm convinced that overlapping node networks is something that won't be possible to handle on the waymarkedtrails map anyway. So I'll stay with completely ignoring the `network` tag when `network:type` is present.

I'll close the discussion here because, frankly, I don't think it's going anywhere useful. If something else needs to be said, please bring the discussion back to the tagging mailing list.

The new rendering will likely go live in a couple of days.

**Comment by pelderson** [comment]
Thanks for the quick work! I like the new rendering very much: colour, line width, and the zoomlevels for the routes and the nodes.  Now we can truly tag really regional walking routes in Nederland as rwn.

**Comment by pelderson** [comment]
This https://hiking.waymarkedtrails.org/#?map=13!51.4574!5.146 shows a part of Nederland where the old rendering was far too crowded and you couldn't see true regional routes.. Could hardly see the map. Now it shows all four scopes and the node network perfectly on the map. Great job! Also the new category in the info-panel, well done! 
The texts for About the map may need some attention, I would be happy to help, and translate for NL. 

From the NL community I got one remark: about the node2node relations list, it shows the object id and he would like to see the note there, which is in fact the name of the route. 

Is it an option to display 1. name if present; if not 2. note if present; if not 3. objectnumber? Just for node network routes.

**Comment by lonvia** [comment]
Those 'note' tags are a problem because they (ab)use a field that is commonly used for other things that are not suitable for printing in the route list. The plan is to soonish support 'to' and 'from' tags to display '<from> - <to>' if the name is not present. For node networks, I'll probably just use the node refs on the first and last node of the route.

Anyway, that's a different topic. Closing this one. The new rendering is now fully in production.

**Comment by pelderson** [comment]
I've started the discussion about the (ab)use of the note tag. We could
simply use the name-tag or the ref-tag. Both display in the
navigation-panel. Displaying from-to also sounds good. Matter closed for
now!

Fr gr Peter Elderson


Op vr 25 okt. 2019 om 21:24 schreef Sarah Hoffmann <notifications@github.com

**Comment by lonvia** [comment]
Please do not use the `name` or `ref` tag. That's an abuse that's even worse.

**Comment by pelderson** [comment]
Please tell me why so I can enter this into the discussion?

**Comment by lonvia** [comment]
Because these relations don't have a name or reference.

This discussion is off-topic for this ticket. Locking.
