### ISSUE TITLE
Changed / deleted network nodes remain as ghosts

### ISSUE THREAD

**Issue by robhubi** [waymarkedtrails/waymarked-trails-site#339]
Yesterday I removed the node network tags from 97 guideposts.  Nevertheless they are still rendered as network nodes. There may be a relation to issue  #335 .

Only 1 guidepost (ref=28)  is rendered correctly: [7032333316](https://cycling.waymarkedtrails.org/#guidepost?id=7032333316).
97 guideposts are rendered as node network nodes (see example below, yellow node).
All 98 guideposts are queried here: https://overpass-turbo.eu/s/PiB

### Some details to Changeset [78940379](https://openstreetmap.org/changeset/78940379)

    Added tag 	ref		97
    Deleted tag 	network		94
    Deleted tag 	network:type	94
    Deleted tag 	rcn_ref		97

Nodes with “Deleted tag rcn_ref” only:
7032333317
7032333318
7032333320

### More issues
Unfortunately, not only guideposts, but also some waypoints are affected by this issue. Here is an example near the guidepost ref=20: This node also had the network tags once. At the moment I have no overview how many of them are there.

https://cycling.waymarkedtrails.org/#guidepost?id=7032333314 :
![grafik](https://user-images.githubusercontent.com/38103976/71547235-b74b6f80-299d-11ea-9ca6-231216635ad7.png)

Best wishes and a happy new year!
Robert

**Comment by pelderson** [comment]
+1 I regularly move walking node network nodes (rwn_ref=.. , network:type=node_network) to a different OSM-node. The old node (stripped of its node network tags) remains visible on the WMT hiking map. Example: relation 10488983. The start and end have been relocated to different nodes, now you see both network node numbers double on the map!

**Comment by pelderson** [comment]
Is it possible to give some clue as to if and when this problem might be addressed? I suspect other problems may have the same cause, e.g. [this route](https://hiking.waymarkedtrails.org/#route?id=8792967)  is still shown even though the relation doesn't exist in osm anymore.

(I'm working with data, I am aware deletions can be hard to process because, well, they are deleted. You don't want to live-check all objects at runtime or at every refresh, that takes a lot of IO/bandwidth and processing capacity.  I sometimes use a separate clean-up process, scheduled e.g. weekly. Is that an option?)

**Comment by lonvia** [comment]
It gets addressed when I find the time to work on the map.

**Comment by lonvia** [comment]
Fixed with https://github.com/waymarkedtrails/osgende/commit/e41a0f590cbad7805b6ec595dd482220850d420d

**Comment by pelderson** [comment]
Super!

Best, Peter Elderson

**Comment by robhubi** [comment]
Great!
Robert
