### ISSUE TITLE
support website:map links to external map

### ISSUE THREAD

**Issue by pangoSE** [waymarkedtrails/waymarked-trails-site#340]
Is this an easy change? I could submit a pull request if you want :)
see https://hiking.waymarkedtrails.org/#route?id=9067481 for a route that uses this
see also https://wiki.openstreetmap.org/wiki/Key:website:map
it is used in 440 elements currently, but I intend to populate the swedish relations with this tag when maps are available.

**Comment by lonvia** [comment]
No, sorry, I don't see the point of such a tag. We are on an OpenStreetMap map.

On a more general note, I'm very reluctant to add support for tags that are not either in wide use since a couple of years or have gone through the discussion on the tagging mailing lists and the approval process on the wiki.
