### ISSUE TITLE
Not rendering SAC_SCALE is DANGEROUS

### ISSUE THREAD

**Issue by asashi** [waymarkedtrails/waymarked-trails-site#343]
There is a lot of people out there that maps trails that are not easy, sac_scale 4, 5 and 6, per default they are rendered in the very same way as easy trails even if sac_scale **is** assigned.
This is extremely dangerous for people who hike out there and can't see a visible difference in the rendering of trails of very different difficulty.
SAR teams have already rescue people for this reason, they followed a path marked in the same way as the easy part, but the difficulties were to much high for them.
**This is a real danger in the real world, can you avoid this problem?**
![sernio](https://user-images.githubusercontent.com/5949252/73139052-f7b80f00-4069-11ea-8fce-7b86fe6d8be2.png)
In this picture the trail 419 is an easy one, the red-white-red to M.te Sernio is an easy route and the white-red_dotted again to M.te Sernio is a sac_scale 5 route... all them are rendered in the same way on the map.

Thanks

**Comment by cascafico** [comment]
I think the matter is that rendering engine works on relation tags only. 

Often a trail (hence a relation) is composed by different difficulty segments. IMHO way tags, instead of relation tags, should be considered by rendering,

**Comment by alpterlab** [comment]
In order to mantain the integrity of the relation... wouldnt be possible, for example, allow to render only the segments indicated with sac_scale 4, 5 and 6 on the top of the general relation.... in this way the entire relation is mantained... and the dangerous segments are rendere on the top of it...  

However on the example above I have a little doubt....
The [419 hiking route is this ](https://hiking.waymarkedtrails.org/#route?id=140250&map=16!46.4736!13.1469)
The path that goes up to the Sernio Mountain -  is called [Via normale del Monte Sernio](https://hiking.waymarkedtrails.org/#route?id=140260&map=16!46.4739!13.1467)
The path with SAC Scale 5 in question is ["Via dell'Anello"](https://hiking.waymarkedtrails.org/#route?id=10110672)

**NONE OF THEM GOT neither A SAC SCALE or a CAI SCALE for the entire relation!!!**
If added CAI SCALE to the relation... the rendering would be different... so you can better judge the danger of the route....
In the case of Via dell'Anello the entire path would need a cai_scale=EEA*  and therfore would be rendered as EEA...
**Therefore there is no need  to render the single segments...  cause the maximum difficult passage-segment of a particular route will give the CAI Scale grade to the all relation....in this case the entire route is EEA!**

![cai scale annotation](https://user-images.githubusercontent.com/20671397/75336879-3b31b300-588c-11ea-8209-29320ff756dd.png)

**Comment by lonvia** [comment]
Let's be very clear: waymarkedtrails aims to show you signposted trails, nothing more, nothing less. Your are welcome to use it as a mapper to check your data and and as a user to plan your routes. But you are solely responsible for your own safety. A hike should always be appropriately planned and you never should set out without checking local conditions. If you think you can go anywhere with waymarkedtrails as your only source of information then you are clearly unfit to do so.

Adding SAC_SCALE will change nothing about the situation. On the contrary, it might give visitors a false sensation of safety when they see difficult paths marked on one part of the map but in another. It is very difficult to make it clear that information is missing at these other parts.

So, sac/cai scales will get rendered where it makes sense cartographically. Currently, that's in Switzerland and Italy. Otherwise, sorry, not possible.

**Comment by hungerburg** [comment]
> So, sac/cai scales will get rendered where it makes sense cartographically. Currently, that's in Switzerland and Italy

I do not understand why `sac_scale` gets rendered only in Switzerland. The key is advertised in OSM as a means to let consumers/users know if "you can comfortably walk there in sneakers or need special equipment or scrambling/climbing skills" (quoted from memory.) And that, spanning all of the globe! (Let us pray, this ever will be followed.)

Not knowing how the key is rendered in Switzerland, but observing other consumers that render route relations -- some use different stipples to indicate sac_scale, both in the base layer ways, and also in the route overlay: E.g. solid for `hiking`, dashed for` *mountain_hiking`, dotted for `*alpine_hiking`. I applaud them for that.

I know, OSM `sac_scale` must not be applied to relations (unlike SAC mountain hiking scale, which is only for routes a.k.a relations) -- Shouldn't it be trivial to find the most demanding or difficult way of a relation and apply that to the relation, if not wanting to match way difficulty? How to render of course another book, but stipples proven, again, not knowing how OSM sac_scale is rendered in waymarked trails in Switzerland …
