### ISSUE TITLE
About piste:type=skitour

### ISSUE THREAD

**Issue by amadvance** [waymarkedtrails/waymarked-trails-site#375]
Is it intentional to not shown relations with piste:type=skitour ?

The ways of kind piste:type=downhill and piste:grooming=backcountry are shown but not the relation including them (including also some other ways used for the climb part).

See for example this area: https://slopes.waymarkedtrails.org/#?map=15!45.864!9.4853

You see some ways with piste:type=downhill, but not the relation that contains them with piste:type=skitour: https://www.openstreetmap.org/relation/8016165

If the intention is to not show skitours, likely also the ways with piste:type=downhill and piste:grooming=backcountry should not be shown. Note that the use of this ways is suggested in the official doc at  https://wiki.openstreetmap.org/wiki/Key:piste:type for skitour

**Comment by datendelphin** [comment]
Yes it is intentional to not show ski tours. But I am not sure that simply removing all piste:grooming=backcountry is the right thing. There are intentionally un-groomed, but perfectly save (as in, you don't need to judge yourself if it is save from avalanches) slopes in skiing resorts, usually signed with a few posts along the way.
Not sure how we can efficiently distinguish those pistes in skiing resorts from an alternate descent of a ski tour.

**Comment by amadvance** [comment]
Hi @datendelphin 

Maybe it's possible to remove such ways only if they are included in a relation piste:type=skitour. That could make the trick.

Thanks for the answer anyway. I got the answer I needed, so I'll close the issue.
