### ISSUE TITLE
torusim:wilderness_hut sometimes showing sometimes not

### ISSUE THREAD

**Issue by mindolluin** [waymarkedtrails/waymarked-trails-site#413]
Hi there,

I was looking at wilderness huts (tourism:wilderness_hut) in Sweden when I noticed that some of them are rendered prominently in blue (e.g. https://www.openstreetmap.org/node/5859334675), as they should be. Others of the same type, though, are nearly invisible until you go to very high zoom levels (e.g. https://www.openstreetmap.org/node/5859294990). Looking at the tags I could not find a reason for the different rendering.

Kind regards,

mindolluin

**Comment by lonvia** [comment]
Huts are rendered by the underlying basemap. We have no control over that.

You could report this at https://github.com/gravitystorm/openstreetmap-carto/issues but to be honest, I wouldn't bother. As far as I can see, this is a simple question of too many amenities in one place. It's more or less random which one wins to be displayed. In the particular case of Valkallen, there is an amenity=shelter next to the wilderness hut which should probably be deleted anyway because it is duplicated information and the wilderness hut has the more detailed tagging.
