### ISSUE TITLE
GPX EXport

### ISSUE THREAD

**Issue by tvage** [waymarkedtrails/waymarked-trails-site#414]
The GPX export for Isle of Isle of Wight Coastal Path contains an unexpected trkseg at the end, which is a duplicate of one elsewhere in the file and is some 10 miles away from the previous point. <trkseg><trkpt lat="50.5833562" lon="-1.2868722" /><trkpt lat="50.5832648" lon="-1.2868997" /></trkseg>. After importing into Garmin BaseCamp, the track shows:

4242			86 ft			292.0° true		N50.69305° W1.10811°					
4243			63 ft			295.1° true		N50.69313° W1.10845°					
4244			47 ft			299.1° true		N50.69321° W1.10870°					
4245			10.9 mi		225.8° true		N50.69327° W1.10888°					
4246			34 ft			190.8° true		N50.58336° W1.28687°					

There is nothing obviously wrong in the OSM data at either end of the unwanted line, no breaks, or spurs in the route.

[isle-of-wight-coastal-path.zip](https://github.com/waymarkedtrails/waymarked-trails-site/files/8156528/isle-of-wight-coastal-path.zip)

**Comment by lonvia** [comment]
This is also visible in the elevation profile: https://hiking.waymarkedtrails.org/#route?id=1129666&type=relation&map=12.0/50.6743/-1.3236

**Comment by lonvia** [comment]
Turns out to be a standard issue of unordered relations. Given that the route contains a forward/backward section around [here](https://hiking.waymarkedtrails.org/#route?id=1129666&type=relation&map=18.0/50.5954/-1.3174), the route is not linear anymore and therefore waymarkedtrails can't sort it and uses the order of the members of the relations. The handling will improve once we do proper handling of forward and backward but the gist of it is: for anything that needs an order route (elevation profile, GPX export), a sorted relation will get you the best results.
