### ISSUE TITLE
Should we update github issue link in i18n files？

### ISSUE THREAD

**Issue by LaoshuBaby** [waymarkedtrails/waymarked-trails-site#418]
Looks like @lonvia had already transfer this repo to waymarkedtrails organization, and make a retire announcement in README: https://github.com/waymarkedtrails/waymarked-trails-site/commit/864759d66aff7b5b45a3c6628908b6b9cb9d41a2

But I noticed all text still remaining the username of lonvia. Should I replace them with new organization name?

For example:

https://github.com/waymarkedtrails/waymarkedtrails-website/blob/51ec4cd18189c8c76360203d6659c31bf17d2595/src/i18n/en-gb/helppages.yaml#L347

(Even English version out of date, other language all remain this)

I don't know should I edit raw yaml file automatically, or manual change this text manually on Transifex.

**Comment by lonvia** [comment]
Fixed in https://github.com/waymarkedtrails/waymarkedtrails-website/commit/b46feee75d3a68853864397ef95a9368d2bce9b3.

Please use the link to https://github.com/waymarkedtrails/waymarked-trails-site in the translations. It is correct that this repository should still be used for bugreports even though the code was moved to other repos.
