### ISSUE TITLE
Route label for French name with accented capital letters

### ISSUE THREAD

**Issue by deuzeffe** [waymarkedtrails/waymarked-trails-site#421]
Hello,

I have a problem with road labels (without osmc:symbol or ref tags) whose French names contain accented capital letters.

For example https://openstreetmap.org/relation/14359313 name=Chemin des Écoliers is labelled "Chemi" as if "4 - If a name tag exists, derive a reference from that, first by using only upper-case letters and failing that by using the first letters of the name." 
did not take into account the accented capitalization (yes, in French, capital letters are accented).

Is it possible to improve this type of label, for example by keeping only the capital letter without its accent, which would give "CDE" for our example?

(other example: https://openstreetmap.org/relation/14358838 name=Sentier des Écrevisses)

Thank you for what you can do if there is anything to do.

**Comment by lonvia** [comment]
Fixed in https://github.com/waymarkedtrails/waymarkedtrails-shields/commit/53364eb0265e81ed3874dc4cdb25d3a7ad8f0074.

Please note that the new code will only have an effect on relations when they are updated in the OSM database. Also note that 'Chemin des Écoliers' will abbreviate to 'CÉ' because 'des' is written in lower case.

**Comment by deuzeffe** [comment]
@lonvia Thank you very much for your efficient and very fast fix!
