### ISSUE TITLE
Render marked ways tagged with _trailblazed=*_

### ISSUE THREAD

**Issue by SonnyLidarDTM** [waymarkedtrails/waymarked-trails-site#454]
Please render marked ways like paths or tracks which are tagged with _trailblazed=*_ and not part of a hiking/cycling route. For example by dashed or dotted lines - in opposite to solide lines already used for routes.

There are many ways which aren't part of a route, but trailblazed with symbols/cairns/poles to express their importance for hikers finding and using the correct paths through a natural area.

Such trailblazed ways should be marked in a special map like waymarkedtrails which is adressed to hikers etc. 

There's a discussion in the forum https://community.openstreetmap.org/t/kein-wanderweg-wenn-nicht-in-waymarkedtrails/110268 regarding trailblazed ways and its presentation in hiker's maps like waymarkedtrails.

**Comment by lonvia** [comment]
Using route relations for waymarked routes is the agreed on method to handle these things these days. If you want to use a different system in Austria, then please make a proposal, have a discussion with the whole Austrian community and make sure you get buy-in to use the system in the whole country. Write a wiki page that describes how waymarked hiking trails are to be mapped in Austria and then open a new issue here pointing to the page.

**Comment by hungerburg** [comment]
Maybe a bit of background: This issue was posted to heal a recurring offence of openstreetmap rules, namely: Mapping for the renderer. This comes up again and again - People looking at the waymarkedtrails website and noticing, Austria is quite empty. So they start mapping routes, where there are no routes there, in the openstreetmap sense. The idea behind this issue: If the trailblazed key would be honoured, people would not need to create routes with no on-the-ground evidence just tag ways instead.

To sum it up: There are plenty of paths suitable for hiking, but the maintainers consider them plain ways rather than routes. In contrast to Switzerland, Austria is missing a federalized agency to guard the whole so this is mostly de-centralized. In some OSM medium I even read, that there is a conspiracy at works -- Nothing could be more wrong: There is a plenitude of maintainers keeping paths in shape that might be mapped as thousands of routes, but the partition is only internal administration and not at all conveyed to the public.

**Comment by lonvia** [comment]
You misunderstand the concept of "tagging for the renderer". It means that you deliberately tag something with a different tag to achieve a nice coloring on a map. For example, mapping something as highway=cycleway because you want a blue line appear on the map.

If there is waymarking along multiple paths, then this exists in reality. The consensus in OSM is by now to capture these sequences of paths with the same waymarking in route relations. I do not deny that there is a historical component here of "wanting everything shown in waymarkedtrails" but it doesn't make it "mapping for the renderer". It is just one way of capturing the data. I do consent that it might not have been the best choice everywhere. But it is where we are today and with the approval of node networks the use of route relations for anything waymarked is even more enshrined then ever.

waymarkedtrails is not the only map using these hiking relations but it is often the first stop for mappers checking their data. This means that it does have a certain responsibility to not add stuff to the map that breaks hiking routes for everyone else. Hence my request for a provable consensus in the whole Austrian community and documentation.

And just to be clear: we are talking about hiking paths that are marked in nature with some kind of trailblazing. We are not talking about some unmarked path suitable for hiking (and maybe with a destination sign on large crossroads). Those are covered by other tags like `sac:scale` and are not of interest to waymarkedtrails anyway (as the name of the website says).

**Comment by hungerburg** [comment]
You should have seen some of the routes that people created here - spider webs with all hiking paths maintained by one local chapter of a rambling club in a single relation.

Thank you very much for taking time and especially the last paragraph: It is a pity that current definition of hiking routes - including the node-network kind - fails here; in such a highly touristic place: Consumers would be very much helped by a means to tell apart designated hiking paths from paths just cutting switchbacks (Abschneider von Serpentinen) or whatever gets mapped as a path by contributors.

Route relations have wide support among consumers. They will come up again and again. I will open a topic on the community forum. This will be a long way to go: The most fervent advocates for creating routes to tell consumers where the designated hiking paths are are also the most fervent when requiring following the documentation to the letter. So documentation will have to be special-cased, that is rewritten.

Update: Talk is slow so far in the community forum - https://community.openstreetmap.org/t/wanderwegrelationen-grundsatzliches/110336 - the heat is here https://community.openstreetmap.org/t/trails-use-name-and-or-hiking-route/110106/28 - but this seems to me mostly about naming, about data models mostly in so far as consumers buy in or not.

**Comment by zekefarwell** [comment]
>You misunderstand the concept of "tagging for the renderer". It means that you deliberately tag something with a different tag to achieve a nice coloring on a map. For example, mapping something as highway=cycleway because you want a blue line appear on the map.

Here's an example where someone added all the mountain bike trails in the area to a single relation and tagged it as `route=mtb`.  I can't say for sure that they were motivated to make the trails show up as nice purple lines on waymarkedtrails, but I've seen numerous other examples like this and I can't come up with any other explanation.  Seems like a pretty clear case of mis-tagging (mis-mapping?) for the renderer to me.  Maybe these trails are all sufficiently marked and qualify for inclusion on waymarkedtrails,  but I'm not confident most trail mappers consider this when adding route relations.  It seems like many are perfectly happy to make relations for any and all trails they would like to see highlighted on trail maps like waymarked trails that only render route relations.

https://mtb.waymarkedtrails.org/#route?id=8032979

![Screenshot 2024-03-12 220112](https://github.com/waymarkedtrails/waymarked-trails-site/assets/281482/81380254-3b4d-475c-947b-aab50f2030c0)

**Comment by lonvia** [comment]
If there is no trailblazing in the nature then those routes should likely be removed (creating route relations for unofficial 'community sites' is a pretty big issue with MTB).

However, this is not what this ticket was about. This ticket asked to show trailblazed=* to avoid using route relations. So we are talking about paths clearly marked for hiking/biking.mtb/horse here. Having them in relations is not tagging for the renderer.

**Comment by SonnyLidarDTM** [comment]
> This ticket asked to show trailblazed=* to avoid using route relations.

I'm not sure if my intention come across correctly: The idea is NOT to avoid route relations. They still should be used for "real" routes which are trailblazed or signed with a NAME and/or a REF-number.

But the MTB-paths example above of @zekefarwell are a good example: I doubt that all these ways of MTB-routes have an individual name or ref. But they could still could be trailblazed in some way (e.b. color marks on trees) to define them being prefered paths for mountainbikers intead of other non-trailblazed ways nearby.

In Austria there are a lot of "real" hiking routes with names and/or REF. But on the other hand also a lot of trailblazed-by-colomarks-only paths without any Name, ref, or hiking signposts. These are prefered paths for hikers - but not part of any hiking route or network.

In classic Austrian hiking maps (ÖK50, Kompass, freytag & berndt) these just-trailblazed ways are color-highlighted as well, just like the "real" hiking routes. Often with a slighty different line style (dashed, dotted)

**Comment by lonvia** [comment]
There is no 'real' here. If it is trailblazed it is a hiking route relation in OSM. That's the convention in OSM right now. Your suggestion is to change the convention and introduce other routes. That needs to go through a full proposal process before waymarkedtrails will consider it. Simple as that.

**Comment by 1ec5** [comment]
> If it is trailblazed it is a hiking route relation in OSM.

FYI, [this discussion on the forum](https://community.openstreetmap.org/t/trails-use-name-and-or-hiking-route/110106) and a couple others before it highlight a certain degree of unease about this statement in the context of North American–style route marking (whether based on blazes or other signs).

Currently, there are two dominant styles: one is indeed to create a route relation for anything that is marked on the ground and goes by a certain name. The other is that a trail by a certain name should have no relation and no special tagging, other than the `name` on each way. We’ve been in sort of a quiet stalemate for over a decade because no one is willing to risk letting trails go unmarked on Waymarked Trails and OpenCycleMap, even as the name-based route relations get mixed up with formal walking/cycling/hiking networks. (`network=lcn`  is inaccurate, chosen purely to look less prominent on these two renderers.)

If the outcome of these discussions is a consensus that short-distance named trails don’t warrant anything explicit in OSM, then it would create an expectation that data consumers such as Waymarked Trails would collect identically named trail segments into something visually resembling a route. Otherwise, enforcing this consensus would be a lost cause, because mappers care about the visual presentation on Waymarked Trails. A “tagging” proposal about not tagging anything would be pretty awkward anyways. Perhaps eliminating the relations is too extreme a position; some feedback from developers such as yourself would help us decide on something more workable.

**Comment by osmuser63783** [comment]
Another variant of this is [this situation](https://www.openstreetmap.org/way/298155745):

You drive to a trailhead in the forest and park your car there. There’s a circular, blazed hiking trail that loops around back to the parking lot. There are no forks in the trail and no other way to get there other than driving there. The blazes are only there to make sure you stay on the trail, not to show you which trail to follow at a junction.

It's currently mapped as a single way with a `name` tag, `sac_scale` and `trail_visibility` (missing the `trailblazed` tag).

If there was a route relation, it would only have that one way as a member (plus maybe the parking lot and some information boards).

I think this situation is quite common in the US, so I asked on the community forum what US mappers thought about creating a route relation for this sort of situation. The responses ranged from "yes that's best practice (even if not everyone does it)" to "it's technically wrong and people really only do that because some renderers won't show it otherwise".

I would be curious what you think about this. I think the question for waymarkedtrails is: is this a QA tool that shows route relations? Then just keep it simple. Or is it supposed to be a useful map for hikers that shows all waymarked hiking trails in an area? Then why not consider showing the above example, if it has a `trailblazed` tag, even without a route relation?

**Comment by lonvia** [comment]
I'm aware of these purpose made hiking trails in the US. They really are different in that they are not routes on top of existing paths and ways. If you had asked me 6 years ago, I'd have recommended to just add a few tags that mark them as purpose-made hiking trails and be done with it. It's just the easiest to do for the mapper. Nowadays, my recommendation goes towards using route relations even for those. Two reasons:

* This is not just about displaying on waymarkedtrails. There are dozens of outdoor apps out there, all of which can handle route relations by now. Use relations and you can use all of them right out-of-the-box. Creating a 1-member relation is not so complicated. The average mapper can learn that and it takes little time. You get a lot of uses out of your relation for the little extra work.
* Even in the US the trails are rarely so obviously one way as described in the example by @osmuser63783. You've already mentioned "collecting identically named trail segments", i.e. most trails are indeed not made of one single OSM way. And then you very quickly find the situation where two trails depart from the same trailhead and follow the same path before forking of to the left and rights to become separate trails. How do you handle the shared part? That's the point where I consider it easier to just go with the relations as a general rule and avoid creating more special cases to handle the corner cases.

But that is just my opinion. To repeat what I said above: I'm not against supporting a tag-based tagging schema in waymarkedtrails. It's also fine to do this on a per-country basis. There is just the constraint that it needs to have the support of the community. And that means a proposal process and a Wiki page that explains the rules and that I can point a mapper (or in fact other data users) to, when they ask why waymarkedtrails shows what it shows.

**Comment by hungerburg** [comment]
Rest assured, I will oppose any proposals that aim at making "trailblazed=*" a marker for consumers to learn that a path is in fact "hiking=designated". Both and I am afraid, any cousins, will turn waymarked trails  into a colouring book even more than now. E.g. https://www.openstreetmap.org/way/921865907 - perhaps the first use of this tag (not key). Adding a route relation requires a bit more of a conscious decision than adding a tag.

What bothers me the most about route relations is the requirement to keep members in order, that is sorted. That makes them an ugly to work with data type. But when the next mapper comes in and splits your single hiking trail into dozens of 2 to 20m sections to tag mtb:scale minutely to the ground, manually curated relations certainly outperform crude heuristics. I do not want to look at the code that creates "virtual" relations from winter pistes.

**Comment by zekefarwell** [comment]
> I'm aware of these purpose made hiking trails in the US. They really are different in that they are not routes on top of existing paths and ways. If you had asked me 6 years ago, I'd have recommended to just add a few tags that mark them as purpose-made hiking trails and be done with it. It's just the easiest to do for the mapper. Nowadays, my recommendation goes towards using route relations even for those.

Would you recommend using route relations for official trails that aren't blazed?  Sometimes trails may not have blazes, but are still officially designated by the land managers.  One reason for this can be that the trail is very highly developed and easy to follow so the maintainers don't consider blazing necessary for wayfinding.   Another reason is that wilderness area management plans aim for as little human intervention as possible and this sometimes includes not blazing trails.

**Comment by lonvia** [comment]
> Would you recommend using route relations for official trails that aren't blazed?

We are entering a gray area area here with the question of when does a hiking trail count as "being signed". My approach here would be to apply a liberal on-the-ground rule: 1) there should be evidence in the wild that this path/route is intended as a route for hiking. In the US, I'd consider the maps and route description you usually find at the parking lots at the trail heads sufficient evidence. 2) There should be enough evidence along the route to confirm that you are still following the right path. Trailblazing is obvious evidence. If the trail is a simple path without forks, then that's enough too. If there are forks, I'd expect at least the occasional signpost with a hint to the route.

For 2), repeated signing can become a fairly loose definition. In my area in Germany there are long-distance routes which essentially always follow locally maintained traiblazed paths. Signposts for the long-distance route are rare and only to be found every 10km or so, usually close to important sights. So you can follow the local trailblazing quite well and connect the dots but it's definitely not enough signage to follow the long-distance path without prior knowledge of how it works. For something like the [Canol Trail](https://hiking.waymarkedtrails.org/#route?id=13591414&type=relation) it'd probably be worse.

In some of the cases you describe, you could also be of the opinion that these are just simple named `highway=path` (possibly with `sac_scale` to designate it as a hiking path), especially when the information board at the trail head just shows you a maze of paths and you can't get to your destination without a map.
